In [1]:
%reset -f 
# This command resets the kernel.

In [2]:
pwd

'/Users/david/Downloads'

In [3]:
import sys
# the mock-0.3.1 dir contains testcase.py, testutils.py & mock.py
sys.path.append('/Users/David/downloads')
import illustris_python.snapshot2 as ilsnap

In [4]:
import illustris_python as il
import numpy as np
import random as rand
import matplotlib.pyplot as plot
from mpl_toolkits.mplot3d import axes3d  
import math

In [5]:
import h5py

In [6]:
basePath = '/Users/david/Downloads'

In [ ]:
#ls /Users/david/Downloads/snapdir_800/snap_800.0.hdf5

In [7]:
snapNum = 600 #Defines snapshot number we are currently using

In [8]:
dm = ilsnap.loadSubset(basePath, snapNum,"DM", fields=['Coordinates'])

In [9]:
dm

array([[ 23274.02903032, 169782.40500616,   7595.80536087],
       [ 23370.78184566, 169823.51788749,   7596.8966095 ],
       [ 23299.63276627, 169921.17204761,   7537.15696149],
       ...,
       [ 27370.20624462, 180785.88964963,  22472.00927571],
       [ 27455.69799985, 180787.93598671,  22453.22516969],
       [ 27446.78788134, 180843.80946621,  22421.40095512]])

In [10]:
with h5py.File('subbox1_99.hdf5','r') as f:
    snap_sub = f['FullBoxSnapNum'][()]

In [11]:
snap_sub

array([-1, -1, -1, ..., -1, -1, 99], dtype=int16)

In [12]:
non_neg = []
val = -2
for i in range(len(snap_sub)):
    if snap_sub[i] > -1:
        val = snap_sub[i]
    non_neg.append(val)

In [13]:
non_neg

[-2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0

In [14]:
np.unique(non_neg)
# This shows all the fullbox snapshots that have correalted snapshots in the subbox. 

array([-2,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
# To continue this analysis, we want to find the snapshot with the highest time resolution. According to a table on 
#the TNG website, the subboxes for TNG100 will have the highest time resolution when the redshift is 6. The fullbox
#snapshot of 13 has a redshift close to 6. Thus, we want to find the subbox snapshot that correaltes to the fullbox
#snapshot of 13. 

In [15]:
non_neg.index(13) #This searches for the location of the value "13". The index that contains "13" will be the 
#snapshot in the subbox that corresponds to the thirteenth snapshot in the fullbox. 

613

In [16]:
snap_sub[613]

13

In [17]:
snapNum2 = 13 #Creating avariable to define the thirteenth snapshot of the TNG100-1 fullbox 

In [18]:
basePath2 = '/Users/david/Downloads'   
#Creating a directory to access the group catalog of the thirteenth snapshot of the TNG100-1 fullbox 
            

In [22]:
fof_halo = il.groupcat.loadHalos(basePath2, snapNum2, fields=['GroupFirstSub'])
fof_halo

array([       0,       40,       78, ..., 11737901, 11737902, 11737903],
      dtype=int32)

In [23]:
len(fof_halo)

11957063

In [24]:
with h5py.File('subbox1_99.hdf5','r') as f:
    id = f['SubhaloIDs'][()]

In [25]:
id

array([   78522,    78523,    78524, ..., 14245910, 14247393, 14248522])

In [26]:
len(id)

15567

In [27]:
def common_member(a, b):
#    matches = []
    a_set = set(a)
    b_set = set(b)
    #print(b_set)
    if (a_set & b_set):
        matches=list(a_set & b_set)
    else:
        print("No common elements")
    return matches

In [ ]:
#def common_element(a, b):
    #matches = []
    #a_list = a
    #b_list = b
    #for i in range(len(a_list)):
        #q = a_list[i]
        #if (i%(int(len(range(len(a_list)))*0.01)) == 0):
            #print(f"{round(i/(len(a_list))*100)} % completed")
        #for j in range(len(b_list)):
            #r = b_list[j]
            #if (q == r):
                #matches.append(q)
    #return matches

In [28]:
a = fof_halo
b = id

temp=common_member(a, b)

In [29]:
np.sort(id)

array([   78522,    78523,    78524, ..., 14245910, 14247393, 14248522])

In [30]:
len(temp)

10877

In [31]:
temp

[3506176,
 9109512,
 3407881,
 7307282,
 5505050,
 7340060,
 6520861,
 8388638,
 10190884,
 2916393,
 2916394,
 7274538,
 8060973,
 10092592,
 6389811,
 10092596,
 3637306,
 10092605,
 8388680,
 4390985,
 9109579,
 7569484,
 9797710,
 10092624,
 4391000,
 9601120,
 10190956,
 2883694,
 2883695,
 11501680,
 9109618,
 5177462,
 9896063,
 7340173,
 5505166,
 10420365,
 7307411,
 5669018,
 5669019,
 6586529,
 10092709,
 7962792,
 5832875,
 7012525,
 5767343,
 2949317,
 5669070,
 3702998,
 7307479,
 5374168,
 4391133,
 2556126,
 9109727,
 11206878,
 11665631,
 11501795,
 3604708,
 5374181,
 11206886,
 9109750,
 5243127,
 10420473,
 9896186,
 5964032,
 4391169,
 7340288,
 5505286,
 5669128,
 5669129,
 6684939,
 6684940,
 9896208,
 3375380,
 6586667,
 9437484,
 2425133,
 2425134,
 2425135,
 5243185,
 10191154,
 10420536,
 5505342,
 10420544,
 3375428,
 3113288,
 9699657,
 5669196,
 3375439,
 10092890,
 6160731,
 9994589,
 5243237,
 3604839,
 786792,
 786793,
 6586730,
 786795,
 10092907,
 786

In [32]:
np.where(fof_halo == 6193966)


(array([5620828]),)

In [33]:
fof_halo[5620828]

6193966

In [ ]:
#dm = il.snapshot.loadSubset(basePath, snapNum,"DM", fields=['SubhaloIDs'])

In [34]:
np.where(id == 6193966)

(array([9274]),)

In [35]:
id[9274]

6193966

In [36]:
np.where(fof_halo == 7570258)

(array([7068757]),)

In [37]:
fof_halo[7068757]

7570258

In [38]:
np.where(id == 7570258)

(array([10589]),)

In [39]:
id[10589]

7570258

In [40]:
non_index = []
for i in range(len(id)):
    k = id[i]
    if k not in fof_halo:
        non_index.append(k) 

In [41]:
non_index

[78523,
 78524,
 78525,
 78526,
 78528,
 78530,
 78531,
 78532,
 78534,
 78535,
 78536,
 78538,
 78540,
 78541,
 78542,
 78544,
 78545,
 78546,
 78547,
 78548,
 78550,
 78551,
 78554,
 78557,
 78559,
 78560,
 78562,
 78563,
 78564,
 78566,
 78567,
 78568,
 78569,
 78570,
 78571,
 78573,
 78574,
 78575,
 78576,
 78577,
 78579,
 78580,
 78581,
 78582,
 78583,
 78586,
 78587,
 78588,
 78589,
 78591,
 78593,
 78595,
 78596,
 78598,
 78599,
 78600,
 78602,
 78605,
 78606,
 78607,
 78608,
 78609,
 78611,
 78612,
 78613,
 78614,
 78615,
 78618,
 78619,
 78620,
 78621,
 78622,
 78624,
 78625,
 78626,
 78628,
 78631,
 78632,
 78633,
 78634,
 78635,
 78637,
 78639,
 78642,
 78643,
 78644,
 78645,
 78646,
 78648,
 78649,
 78651,
 78652,
 78653,
 78656,
 78658,
 78659,
 78660,
 78661,
 78662,
 78664,
 78666,
 78667,
 78668,
 78669,
 78670,
 78673,
 78674,
 78676,
 78677,
 78678,
 78680,
 78682,
 78683,
 78687,
 78688,
 78689,
 78690,
 78692,
 78693,
 78694,
 78698,
 78699,
 78700,
 78702,
 78703,


In [42]:
len(non_index)

4690

In [53]:
np.sort(id)

array([   78522,    78523,    78524, ..., 14245910, 14247393, 14248522])

In [54]:
lim_fof_halo = []
for i in range(len(fof_halo)):
    g = fof_halo[i]
    if g >= 78522:
        lim_fof_halo.append(g)
        
#We now want to determine 

In [55]:
lim_fof_halo

[78522,
 78527,
 78529,
 78533,
 78537,
 78539,
 78543,
 78549,
 78552,
 78553,
 78555,
 78556,
 78558,
 78561,
 78565,
 78572,
 78578,
 78584,
 78585,
 78590,
 78592,
 78594,
 78597,
 78601,
 78603,
 78604,
 78610,
 78616,
 78617,
 78623,
 78627,
 78629,
 78630,
 78636,
 78638,
 78640,
 78641,
 78647,
 78650,
 78654,
 78655,
 78657,
 78663,
 78665,
 78671,
 78672,
 78675,
 78679,
 78681,
 78684,
 78685,
 78686,
 78691,
 78695,
 78696,
 78697,
 78701,
 78709,
 78711,
 78714,
 78721,
 78725,
 78729,
 78732,
 78734,
 78736,
 78741,
 78742,
 78749,
 78755,
 78759,
 78764,
 78770,
 78776,
 78779,
 78782,
 78783,
 78785,
 78789,
 78791,
 78795,
 78800,
 78804,
 78806,
 78812,
 78815,
 78821,
 78827,
 78828,
 78831,
 78834,
 78838,
 78840,
 78843,
 78845,
 78849,
 78852,
 78855,
 78859,
 78861,
 78866,
 78869,
 78874,
 78876,
 78881,
 78889,
 78891,
 78894,
 78896,
 78903,
 78904,
 78906,
 78913,
 78914,
 78919,
 78923,
 78926,
 78929,
 78931,
 78933,
 78937,
 78939,
 78944,
 78950,
 78952,


In [56]:
tot_lim_fof_halo =[]
for i in range(len(lim_fof_halo)):
    h = lim_fof_halo[i]
    if h <= 14248522:
        tot_lim_fof_halo.append(h)

In [57]:
len(tot_lim_fof_halo)

11093732

In [47]:
tot_lim_fof_halo

[194948,
 194949,
 194950,
 194951,
 194952,
 194954,
 194958,
 194960,
 194963,
 194965,
 194972,
 194974,
 194979,
 194984,
 194988,
 194990,
 194994,
 194996,
 194999,
 195000,
 195007,
 195008,
 195010,
 195011,
 195014,
 195017,
 195019,
 195024,
 195026,
 195029,
 195032,
 195034,
 195035,
 195039,
 195043,
 195044,
 195045,
 195046,
 195048,
 195049,
 195051,
 195052,
 195054,
 195058,
 195062,
 195063,
 195065,
 195066,
 195068,
 195070,
 195071,
 195072,
 195075,
 195078,
 195080,
 195082,
 195084,
 195086,
 195089,
 195094,
 195096,
 195100,
 195103,
 195107,
 195112,
 195116,
 195117,
 195118,
 195119,
 195122,
 195123,
 195124,
 195126,
 195128,
 195131,
 195133,
 195136,
 195138,
 195142,
 195143,
 195145,
 195146,
 195148,
 195152,
 195155,
 195157,
 195159,
 195164,
 195167,
 195168,
 195171,
 195175,
 195178,
 195179,
 195180,
 195184,
 195188,
 195189,
 195191,
 195193,
 195194,
 195195,
 195197,
 195198,
 195199,
 195200,
 195201,
 195204,
 195208,
 195211,
 195215,
 

In [48]:
list_halo_1 = fof_halo.tolist()
list_halo_1

[0,
 40,
 78,
 112,
 135,
 162,
 205,
 233,
 278,
 311,
 356,
 381,
 417,
 448,
 481,
 499,
 524,
 560,
 589,
 600,
 640,
 669,
 682,
 708,
 727,
 757,
 787,
 809,
 840,
 852,
 864,
 895,
 923,
 946,
 956,
 995,
 1019,
 1032,
 1061,
 1087,
 1105,
 1117,
 1140,
 1156,
 1180,
 1193,
 1211,
 1227,
 1248,
 1263,
 1276,
 1296,
 1312,
 1328,
 1351,
 1388,
 1407,
 1415,
 1425,
 1442,
 1463,
 1474,
 1483,
 1505,
 1520,
 1536,
 1558,
 1577,
 1588,
 1602,
 1613,
 1615,
 1634,
 1653,
 1672,
 1685,
 1701,
 1723,
 1737,
 1759,
 1769,
 1789,
 1801,
 1818,
 1826,
 1840,
 1846,
 1869,
 1879,
 1892,
 1914,
 1935,
 1952,
 1958,
 1965,
 1984,
 2001,
 2008,
 2026,
 2052,
 2062,
 2073,
 2089,
 2105,
 2133,
 2146,
 2167,
 2174,
 2181,
 2193,
 2204,
 2218,
 2226,
 2249,
 2267,
 2282,
 2294,
 2303,
 2318,
 2326,
 2339,
 2353,
 2362,
 2376,
 2387,
 2397,
 2411,
 2429,
 2438,
 2449,
 2464,
 2479,
 2509,
 2535,
 2543,
 2562,
 2574,
 2595,
 2606,
 2614,
 2621,
 2628,
 2641,
 2651,
 2661,
 2675,
 2684,
 2694,
 270

In [49]:
len(fof_halo)

11957063

In [50]:
list_halo_1.append(0)
list_halo_1

[0,
 40,
 78,
 112,
 135,
 162,
 205,
 233,
 278,
 311,
 356,
 381,
 417,
 448,
 481,
 499,
 524,
 560,
 589,
 600,
 640,
 669,
 682,
 708,
 727,
 757,
 787,
 809,
 840,
 852,
 864,
 895,
 923,
 946,
 956,
 995,
 1019,
 1032,
 1061,
 1087,
 1105,
 1117,
 1140,
 1156,
 1180,
 1193,
 1211,
 1227,
 1248,
 1263,
 1276,
 1296,
 1312,
 1328,
 1351,
 1388,
 1407,
 1415,
 1425,
 1442,
 1463,
 1474,
 1483,
 1505,
 1520,
 1536,
 1558,
 1577,
 1588,
 1602,
 1613,
 1615,
 1634,
 1653,
 1672,
 1685,
 1701,
 1723,
 1737,
 1759,
 1769,
 1789,
 1801,
 1818,
 1826,
 1840,
 1846,
 1869,
 1879,
 1892,
 1914,
 1935,
 1952,
 1958,
 1965,
 1984,
 2001,
 2008,
 2026,
 2052,
 2062,
 2073,
 2089,
 2105,
 2133,
 2146,
 2167,
 2174,
 2181,
 2193,
 2204,
 2218,
 2226,
 2249,
 2267,
 2282,
 2294,
 2303,
 2318,
 2326,
 2339,
 2353,
 2362,
 2376,
 2387,
 2397,
 2411,
 2429,
 2438,
 2449,
 2464,
 2479,
 2509,
 2535,
 2543,
 2562,
 2574,
 2595,
 2606,
 2614,
 2621,
 2628,
 2641,
 2651,
 2661,
 2675,
 2684,
 2694,
 270

In [51]:
list_halo_2 = fof_halo.tolist()

In [52]:
list_halo_2.insert (0,0)
len(list_halo_2)

11957064

In [58]:
diff = []
for i in range(len(tot_lim_fof_halo)):
    if i == len(tot_lim_fof_halo) - 1:
        break
    z = tot_lim_fof_halo[i+1] - tot_lim_fof_halo[i]
    diff.append(z)
    

In [60]:
np.sort(diff)

array([ 1,  1,  1, ..., 11, 11, 15], dtype=int32)

In [ ]:
#ls /Users/david/Downloads/snapdir_800/snap_subbox1_800.0.hdf5

In [ ]:
#il.snapshot.snapPath(basePath, snapNum, chunkNum=1)

In [ ]:
from scipy import constants #Obtaining the speed of light from scipy constants to calculate times later. 
c = constants.c

In [ ]:
snap_cord =  

In [ ]:
z = #In here will go the center of mass of the halo 

In [ ]:
d = []
for i in range(len()):
    diff = snap_cord['SubhaloCM'][i:i+1,2]-z
    d.append(diff)
    
#This calculates the differences between each galaxies z-component and the z-component of the center of mass of the
#halo. In other words, we are calculating the difference in position between the central projection axis and each 
#galaxy along the line of sight. 
    

In [ ]:
d_km = []
for i in range(len(d)):
    d_version = d[i]
    d_m.append(d_version)



#In this cell we will convert the distances to kilometers so that in the following cell when we find time by dividing
#distance by the speed of light we will have both distance and speed in the correct coordinates 

In [ ]:
t = []

for i in range(len(d)):
    t_diff = d[i]/c
    t.append(t_diff)

#This calculates the time difference along the line of sight between the central projection plane and every subhalo.
#We are simply dividing the distance "d" by the speed of light "c"



In [ ]:
t_ big = max(t)  

#Finding the maximum time difference in the list of time for light to travel between central plane and a galaxy.



In [ ]:
t_ small = min(t)
#Finding the minimum time difference in the list of time for light to travel between central plane and a galaxy.
#Having both the maximimum and minimum time difference are necessary to know how many snapshots before and after the 
#the snapshot used for the central plane will be needed to complete the projection alogritihm. This prevents us
#from downloading an excessive amount of unnecessary snapshots. 

In [ ]:
#In this cell we will create basepaths for all the snapshots we will download to complete the time projection. 






In [ ]:
# Outer loop is for the subbox and the innerloop is for the 