In [ ]:
%reset -f 
# This command resets the kernel.

In [ ]:
pwd

In [3]:
import sys
# the mock-0.3.1 dir contains testcase.py, testutils.py & mock.py
sys.path.append('/Users/David/downloads')
import illustris_python.snapshot2 as ilsnap

In [4]:
import illustris_python as il
import numpy as np
import random as rand
import matplotlib.pyplot as plot
from mpl_toolkits.mplot3d import axes3d  
import math

In [5]:
import h5py

In [6]:
basePath = '/Users/david/Downloads'

In [ ]:
#ls /Users/david/Downloads/snapdir_800/snap_800.0.hdf5

In [7]:
snapNum = 800 #Defines snapshot number we are currently using

In [8]:
dm = ilsnap.loadSubset(basePath, snapNum,"DM", fields=['Coordinates'])

In [9]:
dm

array([[ 5265.99662055, 20697.00144071, 65139.9456835 ],
       [ 5258.67614226, 20664.68497832, 65129.44456812],
       [ 5272.12174651, 20665.27310868, 65124.61756431],
       ...,
       [ 9520.14084455, 16348.31038531, 62149.53655133],
       [ 9406.57680565, 16338.55755293, 62136.15052766],
       [ 9411.16732303, 16394.34433952, 62132.15451385]])

In [10]:
with h5py.File('subbox0_99.hdf5','r') as f:
    snap_sub = f['FullBoxSnapNum'][()]

In [11]:
snap_sub

array([-1, -1, -1, ..., -1, -1, 99], dtype=int16)

In [12]:
non_neg = []
val = -2
for i in range(len(snap_sub)):
    if snap_sub[i] > -1:
        val = snap_sub[i]
    non_neg.append(val)

In [13]:
non_neg

[-2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0

In [14]:
np.unique(non_neg)
# This shows all the fullbox snapshots that have correalted snapshots in the subbox. 

array([-2,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
# To continue this analysis, we want to find the snapshot with the highest time resolution. According to a table on 
#the TNG website, the subboxes for TNG100 will have the highest time resolution when the redshift is 6. The fullbox
#snapshot of 13 has a redshift close to 6. Thus, we want to find the subbox snapshot that correaltes to the fullbox
#snapshot of 13. 

In [15]:
non_neg.index(13) #This searches for the location of the value "13". The index that contains "13" will be the 
#snapshot in the subbox that corresponds to the thirteenth snapshot in the fullbox. 

784

In [16]:
snap_sub[784]

13

In [17]:
snapNum2 = 13 #Creating a variable to define the thirteenth snapshot of the TNG100-1 fullbox 

In [18]:
basePath2 = '/Users/david/Downloads'   
#Creating a directory to access the group catalog of the thirteenth snapshot of the TNG100-1 fullbox 
            

In [19]:
fof_halo = il.groupcat.loadHalos(basePath2, snapNum2, fields=['GroupFirstSub'])
fof_halo[0:40]

array([   0,   83,  148,  207,  284,  345,  386,  455,  551,  619,  697,
        757,  824,  890,  976, 1024, 1066, 1099, 1138, 1196, 1243, 1299,
       1343, 1411, 1467, 1490, 1523, 1555, 1618, 1654, 1710, 1767, 1813,
       1855, 1898, 1936, 1972, 2033, 2062, 2083], dtype=int32)

In [20]:
len(fof_halo)

6073571

In [21]:
with h5py.File('subbox0_99.hdf5','r') as f:
    id = f['SubhaloIDs'][()]

In [22]:
id

array([ 194946,  194947,  194948, ..., 4368867, 4368999, 4369065])

In [23]:
len(id)

17824

In [24]:
def common_member(a, b):
#    matches = []
    a_set = set(a)
    b_set = set(b)
    #print(b_set)
    if (a_set & b_set):
        matches=list(a_set & b_set)
    else:
        print("No common elements")
    return matches

In [ ]:
#def common_element(a, b):
    #matches = []
    #a_list = a
    #b_list = b
    #for i in range(len(a_list)):
        #q = a_list[i]
        #if (i%(int(len(range(len(a_list)))*0.01)) == 0):
            #print(f"{round(i/(len(a_list))*100)} % completed")
        #for j in range(len(b_list)):
            #r = b_list[j]
            #if (q == r):
                #matches.append(q)
    #return matches

In [25]:
a = fof_halo
b = id

temp=common_member(a, b)

In [26]:
np.sort(id)

array([ 194946,  194947,  194948, ..., 4368867, 4368999, 4369065])

In [27]:
len(temp)

14315

In [28]:
temp

[196609,
 196612,
 2228232,
 196617,
 2686984,
 1900554,
 196620,
 3506189,
 196622,
 1900559,
 196625,
 196627,
 196629,
 196631,
 4292631,
 196636,
 2228252,
 4292639,
 196640,
 1474591,
 196642,
 196643,
 196644,
 196646,
 196648,
 196649,
 2195498,
 2162729,
 3670056,
 1245229,
 196654,
 196655,
 1900589,
 196657,
 1081394,
 196659,
 4292659,
 1146932,
 1146933,
 1245235,
 196664,
 1081395,
 1146938,
 196667,
 3506230,
 196669,
 3506231,
 1081407,
 1572924,
 196673,
 1409090,
 196676,
 196679,
 196680,
 2228296,
 196682,
 2031687,
 1900621,
 196686,
 196688,
 1146960,
 196690,
 3506259,
 524372,
 1146964,
 524373,
 196695,
 524374,
 524376,
 524377,
 524378,
 196700,
 1146973,
 2162781,
 196703,
 524379,
 524380,
 196706,
 524382,
 524383,
 196709,
 3670110,
 524385,
 524386,
 524388,
 196714,
 196715,
 524389,
 196717,
 3506285,
 196719,
 196720,
 524393,
 524396,
 524399,
 196724,
 1900661,
 2162806,
 196727,
 1900662,
 196729,
 4128883,
 4128887,
 196733,
 3506301,
 1900669,
 19

In [ ]:
#for i in range(len(fof_halo)):
    #index = fof_halo[i]
    #for j in range(len(id)):
       # q = id[j]
        #if q >= index and q< index + 1:
            #non_index = list(q)
#return non_index        

In [29]:
non_index = []
for i in range(len(id)):
    k = id[i]
    if k not in fof_halo:
        non_index.append(k) 

In [30]:
non_index

[194947,
 194948,
 194949,
 194950,
 194952,
 194953,
 194957,
 194959,
 194960,
 194963,
 194966,
 194967,
 194969,
 194970,
 194971,
 194973,
 194976,
 194977,
 194978,
 194979,
 194980,
 194981,
 194983,
 194985,
 194988,
 194994,
 194995,
 194996,
 194998,
 195001,
 195008,
 195010,
 195011,
 195014,
 195015,
 195016,
 195018,
 195019,
 195021,
 195023,
 195026,
 195030,
 195031,
 195033,
 195035,
 195037,
 195038,
 195044,
 195045,
 195047,
 195048,
 195049,
 195050,
 195052,
 195054,
 195055,
 195057,
 195058,
 195059,
 195061,
 195063,
 195064,
 195067,
 195068,
 195070,
 195074,
 195075,
 195080,
 195081,
 195083,
 195084,
 195085,
 195086,
 195087,
 195089,
 195090,
 195093,
 195094,
 195096,
 195098,
 195099,
 195101,
 195103,
 195104,
 195106,
 195108,
 195109,
 195110,
 195112,
 195114,
 195116,
 195118,
 195119,
 195121,
 195123,
 195124,
 195125,
 195128,
 195129,
 195130,
 195132,
 195133,
 195134,
 195136,
 195137,
 195138,
 195140,
 195142,
 195143,
 195144,
 195145,
 

In [31]:
17824 - 14315

3509

In [32]:
len(non_index)

3509

In [33]:
lim_fof_halo = []
for i in range(len(fof_halo)):
    g = fof_halo[i]
    if g >= 194946:
        lim_fof_halo.append(g)
        
#We now want to determine 

In [34]:
lim_fof_halo

[194946,
 194951,
 194954,
 194955,
 194956,
 194958,
 194961,
 194962,
 194964,
 194965,
 194968,
 194972,
 194974,
 194975,
 194982,
 194989,
 194991,
 194992,
 194993,
 194997,
 194999,
 195000,
 195002,
 195003,
 195006,
 195007,
 195009,
 195013,
 195017,
 195020,
 195022,
 195024,
 195025,
 195027,
 195029,
 195032,
 195036,
 195039,
 195041,
 195042,
 195043,
 195046,
 195051,
 195053,
 195056,
 195060,
 195062,
 195065,
 195066,
 195069,
 195071,
 195073,
 195076,
 195077,
 195078,
 195079,
 195082,
 195088,
 195091,
 195092,
 195095,
 195097,
 195100,
 195102,
 195105,
 195107,
 195111,
 195113,
 195115,
 195117,
 195120,
 195122,
 195126,
 195127,
 195131,
 195135,
 195139,
 195141,
 195146,
 195147,
 195149,
 195154,
 195155,
 195158,
 195159,
 195161,
 195164,
 195166,
 195169,
 195170,
 195174,
 195176,
 195180,
 195181,
 195185,
 195186,
 195189,
 195191,
 195192,
 195198,
 195200,
 195203,
 195206,
 195211,
 195213,
 195214,
 195216,
 195218,
 195221,
 195225,
 195228,
 

In [35]:
tot_lim_fof_halo =[]
for i in range(len(lim_fof_halo)):
    h = lim_fof_halo[i]
    if h <= 4369065:
        tot_lim_fof_halo.append(h)

In [36]:
len(tot_lim_fof_halo)

3899641

In [37]:
tot_lim_fof_halo

[194946,
 194951,
 194954,
 194955,
 194956,
 194958,
 194961,
 194962,
 194964,
 194965,
 194968,
 194972,
 194974,
 194975,
 194982,
 194989,
 194991,
 194992,
 194993,
 194997,
 194999,
 195000,
 195002,
 195003,
 195006,
 195007,
 195009,
 195013,
 195017,
 195020,
 195022,
 195024,
 195025,
 195027,
 195029,
 195032,
 195036,
 195039,
 195041,
 195042,
 195043,
 195046,
 195051,
 195053,
 195056,
 195060,
 195062,
 195065,
 195066,
 195069,
 195071,
 195073,
 195076,
 195077,
 195078,
 195079,
 195082,
 195088,
 195091,
 195092,
 195095,
 195097,
 195100,
 195102,
 195105,
 195107,
 195111,
 195113,
 195115,
 195117,
 195120,
 195122,
 195126,
 195127,
 195131,
 195135,
 195139,
 195141,
 195146,
 195147,
 195149,
 195154,
 195155,
 195158,
 195159,
 195161,
 195164,
 195166,
 195169,
 195170,
 195174,
 195176,
 195180,
 195181,
 195185,
 195186,
 195189,
 195191,
 195192,
 195198,
 195200,
 195203,
 195206,
 195211,
 195213,
 195214,
 195216,
 195218,
 195221,
 195225,
 195228,
 

In [38]:
list_halo_1 = fof_halo.tolist()
list_halo_1

[0,
 83,
 148,
 207,
 284,
 345,
 386,
 455,
 551,
 619,
 697,
 757,
 824,
 890,
 976,
 1024,
 1066,
 1099,
 1138,
 1196,
 1243,
 1299,
 1343,
 1411,
 1467,
 1490,
 1523,
 1555,
 1618,
 1654,
 1710,
 1767,
 1813,
 1855,
 1898,
 1936,
 1972,
 2033,
 2062,
 2083,
 2130,
 2187,
 2235,
 2270,
 2298,
 2331,
 2349,
 2383,
 2421,
 2463,
 2484,
 2510,
 2547,
 2591,
 2629,
 2655,
 2691,
 2722,
 2784,
 2841,
 2875,
 2900,
 2935,
 2955,
 2978,
 3017,
 3049,
 3065,
 3087,
 3128,
 3156,
 3175,
 3191,
 3226,
 3252,
 3270,
 3299,
 3332,
 3370,
 3413,
 3434,
 3461,
 3476,
 3511,
 3563,
 3592,
 3639,
 3679,
 3702,
 3753,
 3791,
 3853,
 3878,
 3918,
 3940,
 3953,
 3980,
 4009,
 4047,
 4082,
 4106,
 4125,
 4174,
 4215,
 4252,
 4278,
 4291,
 4323,
 4340,
 4354,
 4377,
 4403,
 4427,
 4450,
 4468,
 4498,
 4528,
 4562,
 4575,
 4594,
 4619,
 4635,
 4655,
 4688,
 4731,
 4758,
 4785,
 4806,
 4828,
 4870,
 4889,
 4904,
 4929,
 4949,
 4964,
 4991,
 5027,
 5051,
 5080,
 5104,
 5137,
 5154,
 5192,
 5218,
 5234,
 52

In [39]:
len(fof_halo)

6073571

In [40]:
list_halo_1.append(0)
list_halo_1

[0,
 83,
 148,
 207,
 284,
 345,
 386,
 455,
 551,
 619,
 697,
 757,
 824,
 890,
 976,
 1024,
 1066,
 1099,
 1138,
 1196,
 1243,
 1299,
 1343,
 1411,
 1467,
 1490,
 1523,
 1555,
 1618,
 1654,
 1710,
 1767,
 1813,
 1855,
 1898,
 1936,
 1972,
 2033,
 2062,
 2083,
 2130,
 2187,
 2235,
 2270,
 2298,
 2331,
 2349,
 2383,
 2421,
 2463,
 2484,
 2510,
 2547,
 2591,
 2629,
 2655,
 2691,
 2722,
 2784,
 2841,
 2875,
 2900,
 2935,
 2955,
 2978,
 3017,
 3049,
 3065,
 3087,
 3128,
 3156,
 3175,
 3191,
 3226,
 3252,
 3270,
 3299,
 3332,
 3370,
 3413,
 3434,
 3461,
 3476,
 3511,
 3563,
 3592,
 3639,
 3679,
 3702,
 3753,
 3791,
 3853,
 3878,
 3918,
 3940,
 3953,
 3980,
 4009,
 4047,
 4082,
 4106,
 4125,
 4174,
 4215,
 4252,
 4278,
 4291,
 4323,
 4340,
 4354,
 4377,
 4403,
 4427,
 4450,
 4468,
 4498,
 4528,
 4562,
 4575,
 4594,
 4619,
 4635,
 4655,
 4688,
 4731,
 4758,
 4785,
 4806,
 4828,
 4870,
 4889,
 4904,
 4929,
 4949,
 4964,
 4991,
 5027,
 5051,
 5080,
 5104,
 5137,
 5154,
 5192,
 5218,
 5234,
 52

In [42]:
list_halo_2 = fof_halo.tolist()

In [43]:
list_halo_2.insert (0,0)
len(list_halo_2)

6073572

In [44]:
diff = []
for i in range(len(list_halo_1)):
    e = list_halo_1[i]
    
    f = list_halo_2[i]
    p = e-f
    diff.append(p)

In [45]:
diff

[0,
 83,
 65,
 59,
 77,
 61,
 41,
 69,
 96,
 68,
 78,
 60,
 67,
 66,
 86,
 48,
 42,
 33,
 39,
 58,
 47,
 56,
 44,
 68,
 56,
 23,
 33,
 32,
 63,
 36,
 56,
 57,
 46,
 42,
 43,
 38,
 36,
 61,
 29,
 21,
 47,
 57,
 48,
 35,
 28,
 33,
 18,
 34,
 38,
 42,
 21,
 26,
 37,
 44,
 38,
 26,
 36,
 31,
 62,
 57,
 34,
 25,
 35,
 20,
 23,
 39,
 32,
 16,
 22,
 41,
 28,
 19,
 16,
 35,
 26,
 18,
 29,
 33,
 38,
 43,
 21,
 27,
 15,
 35,
 52,
 29,
 47,
 40,
 23,
 51,
 38,
 62,
 25,
 40,
 22,
 13,
 27,
 29,
 38,
 35,
 24,
 19,
 49,
 41,
 37,
 26,
 13,
 32,
 17,
 14,
 23,
 26,
 24,
 23,
 18,
 30,
 30,
 34,
 13,
 19,
 25,
 16,
 20,
 33,
 43,
 27,
 27,
 21,
 22,
 42,
 19,
 15,
 25,
 20,
 15,
 27,
 36,
 24,
 29,
 24,
 33,
 17,
 38,
 26,
 16,
 13,
 25,
 17,
 17,
 34,
 16,
 11,
 31,
 33,
 4,
 26,
 21,
 25,
 20,
 19,
 23,
 17,
 39,
 31,
 19,
 43,
 21,
 21,
 14,
 14,
 27,
 13,
 46,
 12,
 16,
 25,
 35,
 27,
 26,
 15,
 17,
 7,
 9,
 26,
 16,
 30,
 21,
 21,
 13,
 13,
 20,
 21,
 26,
 30,
 8,
 15,
 22,
 11,
 34,
 20,
 16,


In [46]:
diff.index(-5519019)

6073558

In [47]:
np.sort(diff_np)

NameError: name 'diff_np' is not defined

In [48]:
len(temp)

14315

In [49]:
len(id)

17824

In [50]:
17824 - 14315

3509

In [51]:
len(tot_lim_fof_halo)

3899641

In [55]:
range(len(id))

range(0, 17824)

In [56]:
list_of_lists = np.zeros((17824, 3899641)) # this needs to be defined as a 2d array of zeros that can accomodate the largest # of subhalos in a halo
for i in range(len(id)): 
    if (i%(int(len(range(len(id)))*0.01)) == 0):
        print(f"{round(i/(len(id))*100)} % completed")
    p = id[i]
    for j in range(len(tot_lim_fof_halo)):
        if p >= tot_lim_fof_halo[j] and p < tot_lim_fof_halo[j+1]:
            list_of_lists[i][j] = p
                    
            
        

0 % completed
1 % completed
2 % completed
3 % completed
4 % completed
5 % completed
6 % completed
7 % completed
8 % completed
9 % completed
10 % completed
11 % completed
12 % completed
13 % completed
14 % completed
15 % completed
16 % completed
17 % completed
18 % completed
19 % completed
20 % completed
21 % completed
22 % completed
23 % completed
24 % completed
25 % completed
26 % completed
27 % completed
28 % completed
29 % completed
30 % completed
31 % completed
32 % completed
33 % completed
34 % completed
35 % completed
36 % completed
37 % completed
38 % completed
39 % completed
40 % completed
41 % completed
42 % completed
43 % completed
44 % completed
45 % completed
46 % completed
47 % completed
48 % completed
49 % completed
50 % completed
51 % completed
52 % completed
53 % completed
54 % completed
55 % completed
56 % completed
57 % completed
58 % completed
59 % completed
60 % completed
61 % completed
62 % completed
63 % completed
64 % completed
65 % completed
66 % completed
67 % 

IndexError: list index out of range

In [57]:
 list_of_lists

array([[194946.,      0.,      0., ...,      0.,      0.,      0.],
       [194947.,      0.,      0., ...,      0.,      0.,      0.],
       [194948.,      0.,      0., ...,      0.,      0.,      0.],
       ...,
       [     0.,      0.,      0., ...,      0.,      0.,      0.],
       [     0.,      0.,      0., ...,      0.,      0.,      0.],
       [     0.,      0.,      0., ...,      0.,      0.,      0.]])

In [ ]:

list_of_listslist_of_lists = [[]] * len(tot_lim_fof_halo)

In [ ]:
#We now need to figure out how to get a count of which subhalos in the list non_index belong to which subhalo.


In [ ]:
#ls /Users/david/Downloads/snapdir_800/snap_subbox1_800.0.hdf5

In [ ]:
from scipy import constants #Obtaining the speed of light from scipy constants to calculate times later. 
c = constants.c

In [ ]:
snap_cord =  

In [ ]:
z = #In here will go the center of mass of the halo 

In [ ]:
d = []
for i in range(len()):
    diff = snap_cord['SubhaloCM'][i:i+1,2]-z
    d.append(diff)
    
#This calculates the differences between each galaxies z-component and the z-component of the center of mass of the
#halo. In other words, we are calculating the difference in position between the central projection axis and each 
#galaxy along the line of sight. 
    

In [ ]:
d_km = []
for i in range(len(d)):
    d_version = d[i]
    d_m.append(d_version)



#In this cell we will convert the distances to kilometers so that in the following cell when we find time by dividing
#distance by the speed of light we will have both distance and speed in the correct coordinates 

In [ ]:
t = []

for i in range(len(d)):
    t_diff = d[i]/c
    t.append(t_diff)

#This calculates the time difference along the line of sight between the central projection plane and every subhalo.
#We are simply dividing the distance "d" by the speed of light "c"



In [ ]:
t_ big = max(t)  

#Finding the maximum time difference in the list of time for light to travel between central plane and a galaxy.



In [ ]:
t_ small = min(t)
#Finding the minimum time difference in the list of time for light to travel between central plane and a galaxy.
#Having both the maximimum and minimum time difference are necessary to know how many snapshots before and after the 
#the snapshot used for the central plane will be needed to complete the projection alogritihm. This prevents us
#from downloading an excessive amount of unnecessary snapshots. 

In [ ]:
#In this cell we will create basepaths for all the snapshots we will download to complete the time projection. 




