In [1]:
a = [1,2,3,4,5]
b = [2,4,6,8,10]

In [3]:
import numpy as np

In [4]:
np_a = np.array([1,2,3,4,5])
np_b = np.array([2,4,6,8,10])

In [5]:
np_a + np_b

array([ 3,  6,  9, 12, 15])

In [6]:
np_a

array([1, 2, 3, 4, 5])

In [7]:
np_a.dtype

dtype('int64')

In [8]:
np_a[0] = 10.5

In [9]:
np_a
# Note that all elements in a numpy array must be of the same data type

array([10,  2,  3,  4,  5])

In [10]:
np.sin(np_a)

array([-0.54402111,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [11]:
np.cos(np_a)

array([-0.83907153, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [12]:
type(np_a)

numpy.ndarray

In [14]:
a = np.array([[1,2,3],[4,5,6]])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a[1,1]

5

In [18]:
l = a.tolist()
l

[[1, 2, 3], [4, 5, 6]]

In [19]:
np.array([0,1,2,3])

array([0, 1, 2, 3])

In [20]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [21]:
a = np.array([0,1,2,3])

In [22]:
a

array([0, 1, 2, 3])

In [23]:
a.dtype

dtype('int64')

In [24]:
a = np.array([1,2,3], dtype = 'int32')

In [25]:
a.dtype

dtype('int32')

In [26]:
b = a.astype('int64')  #"astype" will cast the elements of the array as a certain datatype 

In [27]:
b

array([1, 2, 3])

In [28]:
b.dtype

dtype('int64')

In [29]:
a.ndim   #"ndim" tells us the dimensions of the array 

1

In [30]:
a = np.array([[1,2,3],[4,5,6]])

In [31]:
a.ndim

2

In [32]:
a.shape  "Shape" tells us the size of each dimension 

(2, 3)

In [33]:
a.size  #"size" tells how many elements are contained within the array 

6

In [34]:
a.itemsize

8

In [35]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [36]:
a + b #numpy handles things element by element; as you can see, a + b yields a new array in which corresponding 
       # elements of a and b are added together

array([3, 5, 7, 9])

In [37]:
a * b

array([ 2,  6, 12, 20])

In [38]:
a ** b

array([   1,    8,   81, 1024])

In [39]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [40]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [42]:
x = np.arange(11.0)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
x.dtype

dtype('float64')

In [44]:
x * 5  #Multiplying an array by a value results in each element being multiplied by this factor 

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [45]:
np.pi

3.141592653589793

In [46]:
np.e

2.718281828459045

In [47]:
x = (2.0 * np.pi)/10.0

In [48]:
x

0.6283185307179586

In [51]:
x = np.arange(11.0)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [50]:
x[0]

0.0

In [52]:
a = np.array([0,1,2,3])

In [53]:
a[0]

0

In [54]:
a[0] = 10  #This allwos us to 

In [55]:
a

array([10,  1,  2,  3])

In [56]:
a = np.array([0,1,2,3])

In [58]:
a.fill(-4)
a

array([-4, -4, -4, -4])

In [61]:
a = np.array([[0,1,2,3],[10,11,12,13]])



In [62]:
a[1]

array([10, 11, 12, 13])

In [64]:
a = np.array([10,11,12,13,14])

In [65]:
a[1:3]

array([11, 12])

In [66]:
a[:3]

array([10, 11, 12])

In [67]:
a[-2:]

array([13, 14])

In [68]:
a[::2]

array([10, 12, 14])

In [69]:
a = ([0,1,2,3,4])

In [74]:
a[-2:] = 99

TypeError: can only assign an iterable

In [71]:
a

[0, 1, 2, 99, 4]

In [75]:
a = np.arange(25).reshape(5, 5)

In [76]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [81]:
a[:,1]

array([ 1,  6, 11, 16, 21])

In [79]:
a[:,3]

array([ 3,  8, 13, 18, 23])

In [82]:
a[1,0]

5

In [83]:
a[1,2]

7

In [86]:
a[3,0]

15

In [87]:
a[3,2]

17

In [88]:
a[4]

array([20, 21, 22, 23, 24])

In [89]:
yellow = a[4]

In [92]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [94]:
red = a[:, 1::2]
red

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [95]:
a[1::2,]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [96]:
a[1::2, :3:2]

array([[ 5,  7],
       [15, 17]])

In [98]:
from numpy import 

ImportError: cannot import name 'arrange' from 'numpy' (/Users/david/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py)